#To access the config server from the browser:
# http://localhost:8888/product-services/default
# http://localhost:8888/product-services/dev


server.port=8888
spring.application.name=configserver-services
spring.cloud.config.server.git.uri=file:///${user.home}/SpringCloudGitFileLocation


#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
#spring.cloud.discovery.enabled=true

