<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.tutorials.sid.spring</groupId>
		<artifactId>Spring-Cloud-Fundamentals</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>Section-04-Spring-Cloud-Zuul-Proxy-Server</artifactId>
	<packaging>war</packaging>
	<name>Section-04-Spring-Cloud-Zuul-Proxy-Server</name>
	<description>Section-04-Spring-Cloud-Zuul-Proxy-Server</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<Project.name>Section-04-Spring-Cloud-Zuul-Proxy-Server</Project.name>
		<start-class>com.tutorials.sid.spring.Section04SpringCloudZuulProxyServer</start-class>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

		<!-- spring-cloud-starter-sleuth and spring-cloud-sleuth-zipkin were officially deprecated.
       The Last supported version was 3.1.4, which was released in 2021 was supported by Spring boot 2.7.14.
       -->
		<!--<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>-->

		<!-- 2. Replaces spring-cloud-starter-sleuth -->
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-otel</artifactId> <!-- Uses OpenTelemetry bridge -->
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
