spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mydb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/lms

productrestapi.services.url=http://localhost:8080/productmart/productdetails/
logging.file.name=./src/main/resources/log/QA/application.log
spring.thymeleaf.cache=False