<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tutorials.sid.spring</groupId>
        <artifactId>Master-Spring-Boot-3-Spring-Framework-6-with-Java</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>Spring-MOCK-Data-App</artifactId>
    <packaging>jar</packaging>

    <name>Spring-MOCK-Data-App</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <Project.name>Spring-MOCK-Data-App</Project.name>
    </properties>

    <dependencies>
        <!-- JUnit 5 API (version from parent's dependencyManagement) -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <!-- JUnit 5 Engine (version from parent's dependencyManagement) -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
        <!-- Lombok (version from parent's dependencyManagement) -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${Project.name}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <!--The below plugin is used to create an executable JAR file or can call as fat jar which contains all dependencies.
            This will help in to include this module with other applications -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
