<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tutorials.sid.spring</groupId>
        <artifactId>Spring-Tutorials</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>Spring-Boot-Tutorials</artifactId>
    <packaging>pom</packaging>
    <name>Spring-Boot-Tutorials</name>

    <properties>
        <spring.boot.version>3.5.14</spring.boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.14.0</version>
            </dependency>
            <!-- Import Spring Boot BOM to control versions for Spring artifacts -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>8.2.0</version>
                <scope>runtime</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <modules>
        <module>Learn-Spring-boot-in-simple-steps</module>
        <module>Spring-boot-tutorial-for-beginners</module>
        <module>Master-Java-Web-Services-and-RESTful-API-with-Spring-Boot</module>
    </modules>
</project>
